### ISSUE TITLE
IACUC Site Launch & Issues

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#385]
Here is another site that @a-gundy will help us move.

https://www.bethel.edu/academics/iacuc/

We'll decide who will migrate this after Monday. But I wanted to get it in the githubs.

**Comment by annmarieven** [comment]
This site has been migrated but only the index came over because the other pages are behind auth.
https://cms.bethel.edu/entity/access.act?id=e4f507028c58651324d9038d420e464a&type=folder

@a-gundy can you take care of the rest of the build out and clean up and reassign to me when it's ready for proofing? You only need to move over things if they are currently live/being used. You may need to work more directly from the Silva site: https://editor.its.bethel.edu/silva/www/academics/iacuc/edit/tab_edit

Here is the migration grid which you can use to track the status of each page and make any notes on the pages/files.https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=283355292

We'll need to give new system names to all of the files that don't have .doc or .pdf and then setup redirects. :-P Can you create a redirect grid like this one: https://docs.google.com/a/bethel.edu/spreadsheets/d/1CJJLy6B9qPnfZlJYZM2KhSr-3-QQo8IsiHNvqAOdrjg/edit#gid=0 in this folder: https://drive.google.com/drive/u/0/#folders/0B6zZXo3Q3z4VOGFxZS1fZ0FIc1k

This site might be confusing so let me know if you have questions!

**Comment by a-gundy** [comment]
Assigning to @annmarieven for proofing. Redirect grid found at https://docs.google.com/a/bethel.edu/spreadsheets/d/14KMY3sYgzo837s8eIq0oKP_4XAZgkx4xoaWpLisKbBc/edit#gid=0.

**Comment by annmarieven** [comment]
**https://staging.bethel.edu/academics/iacuc/training**
missing link on this page

**https://staging.bethel.edu/academics/iacuc/appendices/**
let's show the title on this page

do a final proof on staging and then reassign to me. thanks @a-gundy !!! :)

**Comment by a-gundy** [comment]
@annmarieven, the missing link is to a page that I didn't migrate to Cascade (the migration spreadsheet said to leave it and it was never published from Silva anyways). Let me know if you want me to move it over anyways. Otherwise everything looks good!

**Comment by annmarieven** [comment]
This site is ready to launch on Thursday. No rule is needed but there are redirects to be put in place.

**Comment by annmarieven** [comment]
@kelslundberg looked in Firefox.
I looked in Safari.

Soda doesn't work with authentication so we weren't able to proof the site because most of it is authenticated.

**Comment by kelslundberg** [comment]
FF looks good

**Comment by annmarieven** [comment]
Site published.
@kelslundberg will annotate.
I contacted web author.
