### ISSUE TITLE
Add "Homepage Proof Point" Tag

### ISSUE THREAD

**Issue by hamtim** [betheluniversity/cascade#425]
@kelslundberg -

In talking with @vedmic and @ErikGruber, we'd like to add an additional tag for proof points, so they could pull to the zone on the homepage for proof points. I know we have the "premiere" tag, but we may need to be even more selective on the homepage.

with cordial sincerity
@hamtim

**Comment by kelslundberg** [comment]
I talked with @ErikGruber about how he wants this to work and we're thinking we'll start by having him build collections of proof points manually since we have that functionality. There's an option to use metadata or to build your own collection. So we'll go the build your own collection route for the homepages for now.
