### ISSUE TITLE
Church Leadership Partnership Migration

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#457]
I'll be migrating the Church Leadership Partnership site. https://www.bethel.edu/academics/partnerships/church-leadership/

**Comment by a-gundy** [comment]
@annmarieven, 
I'm sending this off to you for proofing.

https://staging.bethel.edu/academics/partnerships/church-leadership/

https://cms.bethel.edu/entity/open.act?id=756f287b8c5865132dfb57c86950b95a&type=page&

**Comment by annmarieven** [comment]
can you add this: Practical training for lay leaders and ministry staff of Converge Worldwide. to the teaser on the index page? The teaser field is in the metadata.

on the certificate page, can we list the courses like this:
Church Leadership and Management (ORGL667)
Let's make them bold instead of h3. 

enter descriptions for the org leadership and ministry practice pages.

Once those things are done, can you launch the site, close the old pages, archive the content, and update the grid? https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1762576728

**Comment by a-gundy** [comment]
Launched, made a note in google analytics, and archived.
