### ISSUE TITLE
60 credit prerequisite

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#522]
The Sentence: 

You need to have 60 credits to start this program. Your enrollment counselor can help you explore your options for obtaining credits, including taking courses in our associate degree programs.

**Comment by e-jameson** [comment]
B.A. and B.S. CAPS programs

**Comment by annmarieven** [comment]
Let's put this on the program details page. Below the concentration description and above the white boxes that give the location, start dates, etc.

**Comment by c-schwarze** [comment]
Added. here is an example page

https://staging.bethel.edu/graduate/academics/mba/program-details/management

**Comment by annmarieven** [comment]
Good except for that it's on a GS page. This sentence should only be on BA and BS CAPS programs. :)

Once that's fixed, we should be good to roll it out!

**Comment by annmarieven** [comment]
I'm seeing this on Seminary pages too - https://cms.bethel.edu/entity/open.act?id=99d7f9588c5865135753448210bdb88b&type=page

**Comment by c-schwarze** [comment]
Updated, but not published.

**Comment by annmarieven** [comment]
I will publish one to staging and send it through for approval to Diane Dahl. (don't do nursing)

**Comment by annmarieven** [comment]
hm. I just tried publishing a page to staging to test this and nothing is showing up for me.

https://staging.bethel.edu/adult-undergrad/academics/organizational-leadership/program-details/christian-ministries

**Comment by c-schwarze** [comment]
Oops. It was only working for some. Fixed now.

**Comment by annmarieven** [comment]
@hamtim Here is a page for Diane Dahl to approve (60 credit sentence and core courses). https://staging.bethel.edu/adult-undergrad/academics/organizational-leadership/program-details/christian-ministries

Let me know when it's been approved and I will publish all ba/bs pages to production.

**Comment by hamtim** [comment]
Diane approves the 60 credit language.

For core, she's like it to be "CORE" because "it is a category." She'd also like the descriptive text about CORE added below the heading. She said that text was sent to @vedmic.

**Comment by hamtim** [comment]
Diane sent me the text:

A distinctive feature of Bethel's approach to education is our commitment to the development of the whole person. In addition to courses within a major, CAPS students explore personal values and faith formation in a hospitable environment that respects learning from one another's perspectives. Rather than teaching students what to think about Christianity, we teach students how to think about the bible, Christian history, and personal faith.

I think we can shorten it to:

A distinctive feature of Bethel's programs is our commitment to the development of the whole person. In addition to courses within a program, students explore personal values and faith formation in a hospitable environment that respects learning from one another's perspectives. Rather than teaching students what to think about Christianity, we teach students how to think about the Bible, Christian history, and personal faith.

Ok, so that only took out like 5 words. If it needs to be shorter, Andrea may need to help. But, I'm not sure how much we can shorten. They're picky.

-tim

**Comment by annmarieven** [comment]
@emily-johnson 2 things here.

Can you add this text 'A distinctive feature of Bethel's programs is our commitment to the development of the whole person. In addition to courses within a program, students explore personal values and faith formation in a hospitable environment that respects learning from one another's perspectives. Rather than teaching students what to think about Christianity, we teach students how to think about the Bible, Christian history, and personal faith.' in the program blocks that have core courses listed?

Can you also change the heading from Core Courses to CORE Courses?

When you're done, check the relationships tab of each program block and publish each page to production. Thanks!!

**Comment by emily-johnson** [comment]
I added the description to all of them and changed the heading to "CORE Courses" for the ones that already had that heading. Accounting, Business Management and Nursing have the heading "Select 2 from:" so I left those alone.

**Comment by annmarieven** [comment]
@e-jameson can you add the description field so it shows up on the live pages?

**Comment by e-jameson** [comment]
@annmarieven @emily-johnson Descriptions are one pages now (need to be republished): 

https://staging.bethel.edu/adult-undergrad/academics/organizational-leadership/program-details/christian-ministries

**Comment by annmarieven** [comment]
@emily-johnson can you republish each program details index page (and subsequent concentration pages) for all caps academics programs?

proof each one live before you move onto the next.

thanks!

**Comment by emily-johnson** [comment]
All of the caps program details indexes are republished
