### ISSUE TITLE
URLs linked incorrectly

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#541]
When faculty are entering their professional website URL in the tinker faculty bio form, Cascade is treating it as an internal link and sticking "https://www.bethel.edu/academics/faculty/" in front of whatever they entered (for example see the website link on this site: https://www.bethel.edu/academics/faculty/westmark-michelle). 

Can you code it to treat anything entered as a complete and external URL?
Thanks!

**Comment by e-jameson** [comment]
I think the issue is she did not include the http:// in from the of the URL, so the browser is treating it as a relative link. @c-schwarze, you could probably just if the URL starts with http://, and if not prepend it. We can't do it blindly incase they do include it. 

Also, her website doesn't exist? >_<

**Comment by c-schwarze** [comment]
Fixed.
