### ISSUE TITLE
GS Academic Landing Page

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#544]
These get pretty messy when we try to use the program feed blocks. Any thoughts on how to clean it up?

https://cms.bethel.edu/entity/open.act?id=ba467aa78c58651370c56c6d8de34356&type=page

This was the page before blocks. Ideally we'd have it look something like this:
https://staging.bethel.edu/_testing/erik-test/gs-academics-index

**Comment by annmarieven** [comment]
This goes beyond the academic page too. We'll need to figure something out for admissions pages as well: 
https://staging.bethel.edu/adult-undergrad/admissions/
https://staging.bethel.edu/graduate/admissions/

**Comment by annmarieven** [comment]
@emily-johnson can you try building this page (and making it look nice) -- 
https://staging.bethel.edu/_testing/erik-test/gs-academics-index using the program feed blocks?

then let's move it to /graduate/academics/index

Don't publish to production

**Comment by emily-johnson** [comment]
@johjacb Can we put a white box around the two blocks of program feeds (like the graduate admissions index)? 

https://cms.bethel.edu/entity/open.act?id=fe657b288c58651314811f9c727296d2&type=page

**Comment by emily-johnson** [comment]
We got the white box around all of the feeds and I moved everything to /graduate/academics/

Because we created separate feeds for the index page with the settings we want, there is now a regular and index version of the four feeds (ex: graduate-certificates-program-feed and graduate-certificates-index-program-feed)

Let me know if you want me to change the names of the new feeds, otherwise it is ready for proofing

**Comment by emily-johnson** [comment]
I changed the names of the new indexes to index-graduate-______-program-feed, and moved the original certificate and licensure program feeds into their folders

**Comment by annmarieven** [comment]
this page has launched and is looking good.
