### ISSUE TITLE
Counselor Territories

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#704]
Opening a github for the counselor territory asset updates.

remove title field
make auto page title h2
include admission counselor territories in automatic list 
adjust spacing between photo and text

**Comment by annmarieven** [comment]
When we first rolled out the cas admissions site, we had started to create a counselor territories block. We need some adjustments on it.

For your reference, this is the document we'll be working from: https://docs.google.com/spreadsheets/d/1IT703M0XMPJOkn5YQC8H-bRLRen5JnX_jk_8ba55pqk/edit#gid=0

And here is a test of the territory block: https://cms.bethel.edu/entity/open.act?id=bc6888f88c5865132802f161372e801f&type=page&

- [ ] Should be able to enter single numbers and ranges (ex: 55007 55010 55024 55030-55031 55044 55063-55065 55067-55068 55075-55077 55085 55101-55110)
- [ ] Remove title field (title should just be pulled based on the title of the page)
- [ ] Include admission counselor territories (field from bio page) in the space below the person's job title
- [ ] Adjust spacing between photo and text
- [ ] Person's name (title of the page it's pulling) should be h2

**Comment by c-schwarze** [comment]
Okay I made a bunch of updates. Let me know if there are any other changes that should be made!

**Comment by annmarieven** [comment]
Followed up with Liz to see if those zip codes are accurate. Our students will build it out initially.

**Comment by annmarieven** [comment]
@kathrynmagnuson can you use this google doc: https://docs.google.com/spreadsheets/d/1IT703M0XMPJOkn5YQC8H-bRLRen5JnX_jk_8ba55pqk/edit#gid=0 and load all the data here: https://cms.bethel.edu/entity/open.act?id=cfc882068c58651375fc4ed2ced35038&type=block& (undergrad/admissions/counselors/counselor-territories)

Once you have all the data loaded we'll embed it on the counselors/index page. We'll have to make sure all of the current staff show up and may need to keep the staff listing block if a specific counselor doesn't have zip codes associated with them. For now, just worry about the first part of this description, loading the data, and then we'll figure out the rest once that's done.

You can see a test one that I threw together previously in this issue.

**Comment by c-schwarze** [comment]
From @kathrynmagnuson:
"Hi Caleb, I'm wondering if for the counselor-territories pages, it can be set up so that I can put in nonconsecutive zipcodes separated by commas instead of just consecutive ones with a hyphen or adding a new zipcode field every time. I'll send a screenshot of what I'm trying to do"

![screen shot 2016-04-28 at 11 31 03 am](https://cloud.githubusercontent.com/assets/7849657/14897952/f5e72aa0-0d49-11e6-88dc-6ca7fc7feaf0.png)

**Comment by kathrynmagnuson** [comment]
Can you assign it back to me when this is set up? Thanks!

**Comment by c-schwarze** [comment]
Updated. Let me know if you want any other changes!

**Comment by kathrynmagnuson** [comment]
Yay! Thanks so much!

**Comment by kathrynmagnuson** [comment]
I finished putting in all the zip codes on the block, and published to staging. I tried testing it but it usually comes up with multiple counselors instead of the one associated with that zip code (even though the correct one comes up first on the list). I double checked a few to make sure there weren't errors on the block, could you take a look at it? Thanks! 

https://staging.bethel.edu/undergrad/admissions/counselors/? 
https://cms.bethel.edu/entity/open.act?id=d98ae5a48c586513494909eaf8ce59d6&type=page

**Comment by c-schwarze** [comment]
Could you give a couple of examples that you were having issues with?

**Comment by kathrynmagnuson** [comment]
The zip code "55447" should come up with admissions counselor Geraldine, but both her and Josh appear as results. 
"97001" should be Jenny, but Jenny and Josh come up. "55112" should be Maddie, but Kelli and Maddie come up, etc.

**Comment by c-schwarze** [comment]
It looks like for those examples there appear to be typos. The ranges given include many zip codes. See the screenshots:

![screen shot 2016-04-29 at 3 17 32 pm](https://cloud.githubusercontent.com/assets/7849657/14928450/ae6ecb0e-0e1d-11e6-84a1-2ccbe32a6802.png)
![screen shot 2016-04-29 at 3 17 58 pm](https://cloud.githubusercontent.com/assets/7849657/14928451/ae70187e-0e1d-11e6-82ba-23a9df0388e1.png)
