### ISSUE TITLE
Program Search

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#748]
- [x] Adding display names to CAS concentrations
- [x] Cleaning up the program spreadsheets (@kathrynmagnuson and I)
- [x] Figure out if we can change the Ed. D. title and get rid of the display name
- [x] Hitting enter refreshes the page, and shouldn't
- [x] Trying to make sure delivery options don't get changed when the page refreshes or you hit enter

**Comment by johjacb** [comment]
- [ ] change to 'Associate's', 'Bachelor's', 'Doctoral' in filter
- [ ] remove Compare and Reset all buttons, just leave checkbox
- [ ] remove degree type column and put degree level (Major, Minor, Adult Degree Completion) in that space instead
- [ ] headings for the table section should be: Associate's Degrees, Bachelor's Degrees, Doctoral Degrees

**Comment by c-schwarze** [comment]
@vedmic I finished the updates. Let me know if anything looks wrong.

**Comment by c-schwarze** [comment]
I updated the program search with our changes from our cascade meeting (7/14/16).

* add "'s" to license and certificate
* move compare program buttons to the bottom of the page instead of each table
* Change schools to shorter names (undergrad, adult undergrad, graduate, seminary)
* added help text to the form
